name: nightly-neon

on:
  schedule:
    - cron: "52 23 * * *"
  workflow_dispatch:

env:
  BUILDDIR: /build
  SRCDIR: ${{ github.workspace }}
  CMAKE_ARGS: |
    -DWEBVIEW_FORCE_WEBKIT=1
    -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
    -DWITH_PYTHONQT=OFF"
    -DCMAKE_BUILD_TYPE=Debug

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://kdeneon/plasma:user
      options: --tmpfs /build:rw --user 0:0
    steps:
      - name: "prepare env"
        uses: calamares/actions/prepare-neon@v4
      - name: "prepare source"
        uses: calamares/actions/generic-checkout@v4
      - name: "build"
        id: build
        uses: calamares/actions/generic-build@v4
      - name: "notify: ok"
        if: ${{ success() && github.repository == 'calamares/calamares' }}
        uses: calamares/actions/matrix-notify@v4
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: |
            OK ${{ github.workflow }} in ${{ github.repository }} ${{ steps.build.outputs.git-summary }}
      - name: "notify: fail"
        if: ${{ failure() && github.repository == 'calamares/calamares' }}
        uses: calamares/actions/matrix-notify@v4
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: |
            FAIL ${{ github.workflow }} in ${{ github.repository }} ${{ steps.build.outputs.git-summary }}
      - name: "Calamares: archive"
        working-directory: ${{ env.BUILDDIR }}
        run: |
          make install DESTDIR=${{ env.BUILDDIR }}/stage
          tar czf calamares.tar.gz stage
      - name: "Calamares: upload"
        uses: actions/upload-artifact@v2
        with:
          name: calamares-tarball
          path: ${{ env.BUILDDIR }}/calamares.tar.gz
          if-no-files-found: error
          retention-days: 7
