name: ci-push

on:
  push:
    branches:
      - calamares
      - 3.2.x-stable
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  BUILDDIR: /build
  SRCDIR: ${{ github.workspace }}
  CMAKE_ARGS: |
    -DWEBVIEW_FORCE_WEBKIT=1
    -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
    -DWITH_PYTHONQT=OFF"
    -DCMAKE_BUILD_TYPE=Debug

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://kdeneon/plasma:user
      options: --tmpfs /build:rw --user 0:0
    steps:
      - name: "prepare env"
        uses: calamares/actions/prepare-neon@v4
      - name: "prepare source"
        uses: calamares/actions/generic-checkout@330c45ae1eb6efad4ad75a6dd887c3c5d5fe1590
      - name: "build"
        id: build
        uses: calamares/actions/generic-build@v4
      - name: "notify: ok"
        if: ${{ success() && github.repository == 'calamares/calamares' }}
        uses: calamares/actions/matrix-notify@v4
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: |
            OK ${{ github.workflow }} in ${{ github.repository }} by ${{ github.actor }} on ${{ github.event.ref }}
            .. ${{ steps.build.outputs.git-summary }}
      - name: "notify: fail"
        if: ${{ failure() && github.repository == 'calamares/calamares' }}
        uses: calamares/actions/matrix-notify@v4
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: |
            FAIL ${{ github.workflow }} in ${{ github.repository }} by ${{ github.actor }} on ${{ github.event.ref }}
              .. ${{ steps.build.outputs.git-summary }}
              .. ${{ github.event.compare }}
